platform:
  - x86

configuration:
  - Release

install:
  - SET TYPE=%CONFIGURATION%
  - SET DEVSPACE=%APPVEYOR_BUILD_FOLDER%\..

# dcmtk & zlib
  - cd %DEVSPACE%
  - ps: |
      Invoke-WebRequest http://draconpern-buildcache.s3.amazonaws.com/dcmtk.zip -Outfile "dcmtk.zip"
  - unzip dcmtk.zip

# openjpeg
  - cd %DEVSPACE%
  - git clone --branch=master https://github.com/uclouvain/openjpeg.git
  - cd openjpeg && git checkout openjpeg-2.1 && mkdir build-%TYPE% && cd build-%TYPE%
  - cmake .. -G "Visual Studio 11" -DBUILD_THIRDPARTY=1 -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS_RELEASE="/MT /O2 /D NDEBUG" -DCMAKE_C_FLAGS_DEBUG="/D_DEBUG /MTd /Od" -DCMAKE_INSTALL_PREFIX=%DEVSPACE%\openjpeg\%TYPE%
  - msbuild /P:Configuration=%TYPE% INSTALL.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

#boost
  - cd C:\Libraries\boost_1_59_0
  - call bootstrap
  - IF "%TYPE%" == "Release" b2 toolset=msvc-11.0 runtime-link=static define=_BIND_TO_CURRENT_VCLIBS_VERSION=1 -j 4 --with-thread --with-filesystem --with-system --with-date_time --with-regex --with-context --with-coroutine stage release
  - IF "%TYPE%" == "Debug"   b2 toolset=msvc-11.0 runtime-link=static define=_BIND_TO_CURRENT_VCLIBS_VERSION=1 -j 4 --with-thread --with-filesystem --with-system --with-date_time --with-regex --with-context --with-coroutine stage debug

#fmjpeg2koj
  - cd %DEVSPACE%
  - git clone --branch=master https://github.com/DraconPern/fmjpeg2koj.git
  - cd fmjpeg2koj && mkdir build-%TYPE% && cd build-%TYPE%
  - cmake .. -G "Visual Studio 11" -DBUILD_SHARED_LIBS=OFF -DCMAKE_CXX_FLAGS_RELEASE="/MT /O2 /D NDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="/D_DEBUG /MTd /Od" -DOPENJPEG=%DEVSPACE%\openjpeg\%TYPE% -DDCMTK_DIR=%DEVSPACE%\dcmtk\%TYPE% -DCMAKE_INSTALL_PREFIX=%DEVSPACE%\fmjpeg2koj\%TYPE%
  - msbuild /P:Configuration=%TYPE% INSTALL.vcxproj

#mysql client
  - cd %APPVEYOR_BUILD_FOLDER%
#  - wget https://dev.mysql.com/get/Downloads/Connector-C/mysql-connector-c-6.1.6-src.zip
  - cd mysql-connector-c-6.1.6-src && mkdir build-%TYPE% && cd build-%TYPE%
  - cmake .. -G "Visual Studio 11" -DCMAKE_CXX_FLAGS_RELEASE="/MT /O2 /D NDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="/D_DEBUG /MTd /Od /Zi" -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\mysql-connector-c-6.1.6-src\%TYPE%
  - msbuild /P:Configuration=%TYPE% INSTALL.vcxproj
  - SET MYSQL_DIR=%APPVEYOR_BUILD_FOLDER%\mysql-connector-c-6.1.6-src\%TYPE%

#poco
  - cd %DEVSPACE%
  - git clone https://github.com/pocoproject/poco.git --branch poco-1.6.1 --single-branch
  - cd poco && mkdir build-%TYPE% && cd build-%TYPE%
  - cmake .. -G "Visual Studio 11" -DPOCO_STATIC=ON -DCMAKE_CXX_FLAGS_RELEASE="/MT /O2 /D NDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="/D_DEBUG /MTd /Od /Zi" -DMYSQL_LIB=%APPVEYOR_BUILD_FOLDER%\mysql-connector-c-6.1.6-src\%TYPE%\lib\mysqlclient -DCMAKE_INSTALL_PREFIX=%DEVSPACE%\poco\%TYPE%
  - msbuild /P:Configuration=%TYPE% INSTALL.vcxproj

#simple web server
  - cd %APPVEYOR_BUILD_FOLDER%
  - git clone https://github.com/eidheim/Simple-Web-Server.git
  
before_build:
  - cd %APPVEYOR_BUILD_FOLDER% && mkdir build-%TYPE% && cd build-%TYPE%
  - cmake .. -G "Visual Studio 11" -DBOOST_ROOT=C:\Libraries\boost_1_59_0 -DDCMTK_DIR=%DEVSPACE%\dcmtk\%TYPE% -DZLIB_ROOT=%DEVSPACE%\zlib\%TYPE% -DFMJPEG2K=%DEVSPACE%\fmjpeg2koj\%TYPE% -DOPENJPEG=%DEVSPACE%\openjpeg\%TYPE% -DPOCO=%DEVSPACE%\poco\%TYPE%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build-%TYPE%
  - msbuild /P:Configuration=%TYPE% ALL_BUILD.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%\build-%TYPE%\%TYPE%
  - 7z a fmdscp.zip %APPVEYOR_BUILD_FOLDER%\build-%TYPE%\%TYPE%\fmdscp.exe
  - mv fmdscp.zip %APPVEYOR_BUILD_FOLDER%

artifacts:
  - path: fmdscp.zip
    name: fmdscp
